# ================ test shell ( Sat Mar 14 14:25:15 2020 ) ================
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 3750 --ensemble True --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 3750 --ensemble True --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 3750 --ensemble False --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 3750 --ensemble False --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 5000 --ensemble True --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 5000 --ensemble True --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 5000 --ensemble False --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 5000 --ensemble False --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 6000 --ensemble True --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 6000 --ensemble True --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 6000 --ensemble False --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 6000 --ensemble False --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 8000 --ensemble True --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 8000 --ensemble True --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 8000 --ensemble False --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 8000 --ensemble False --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 10000 --ensemble True --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 10000 --ensemble True --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 10000 --ensemble False --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 10000 --ensemble False --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 12000 --ensemble True --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 12000 --ensemble True --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 12000 --ensemble False --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 12000 --ensemble False --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 14000 --ensemble True --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 14000 --ensemble True --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 14000 --ensemble False --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 14000 --ensemble False --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 16000 --ensemble True --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 16000 --ensemble True --only_Y False
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 16000 --ensemble False --only_Y True
python test.py --dataroot ./datasets\Set5  --name DIV2K_dbpn --model dbpn --load_epoch 16000 --ensemble False --only_Y False
